---
- name: Create appuio-infra project
  openshift_project:
    name: appuio-infra

- name: Instantiate pruner template
  openshift_resource:
    namespace: appuio-infra
    template: "{{ role_path }}/files/pruner-template.yml"
    app_name: appuio-pruner
    arguments:
      PRUNER_VERSION: "{{ appuio_pruner_version | default('master') }}"
      TIMEZONE: "{{ appuio_container_timezone | default('UTC') }}"

- name: Configure permissions for pruner service account
  openshift_policy:
    cluster_roles:
      - edit
      - system:image-pruner      
    users: system:serviceaccount:appuio-infra:default
