---
kind: Template
apiVersion: v1
metadata:
  name: appuio-pruner-job
  annotations:
    description: Install an APPUiO Pruner Job
    version: '2.0.0'

parameters:
  - description: Kind of objects that are pruned, eg "images"
    name: KIND
    required: true

  - description: Image to use for the pruner jobs
    name: IMAGE
    required: true

  - description: Schedule to use for the cronjobs
    name: SCHEDULE
    value: "@hourly"

  - description: Command to execute
    name: COMMAND
    required: true

  - description: CPU request
    name: CPU_REQUEST
    required: true

  - description: CPU limit
    name: CPU_LIMIT
    required: true

  - description: MEMORY request
    name: MEMORY_REQUEST
    required: true

  - description: MEMORY limit
    name: MEMORY_LIMIT
    required: true

objects:

  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: prune-${KIND}
      labels:
        app: appuio-pruner
    spec:
      schedule: ${SCHEDULE}
      failedJobsHistoryLimit: 3
      successfulJobsHistoryLimit: 1
      concurrencyPolicy: Forbid
      startingDeadlineSeconds: 86400
      jobTemplate:
        spec:
          activeDeadlineSeconds: 7200
          completions: 1
          backoffLimit: 2
          template:
            metadata:
              labels:
                name: prune-${KIND}
                app: appuio-pruner
            spec:
              tolerations:
                - effect: NoSchedule
                  key: autoscaled
                  operator: Exists
                - effect: NoSchedule
                  key: appuio.ch/autoscaled
                  operator: Exists
              containers:
                - name: pruner
                  image: ${IMAGE}
                  imagePullPolicy: IfNotPresent
                  command: ${{COMMAND}}
                  args: []
                  resources:
                    requests:
                      cpu: ${{CPU_REQUEST}}
                      memory: ${{MEMORY_REQUEST}}
                    limits:
                      cpu: ${{CPU_LIMIT}}
                      memory: ${{MEMORY_LIMIT}}
              serviceAccountName: pruner
              restartPolicy: Never
