kind: Template
apiVersion: v1
metadata:
  name: pruner
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: appuio-pruner-base
    spec:
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: ${BASE_IMAGE}
          importPolicy:
            scheduled: true
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: appuio-pruner
      creationTimestamp: null
    spec:
      dockerImageRepository: null
    status:
      dockerImageRepository: ''
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: appuio-pruner
      creationTimestamp: null
    spec:
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
      source:
        type: Git
        git:
          uri: '${PRUNER_SOURCE}'
          ref: '${PRUNER_VERSION}'
        secrets: []
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: appuio-pruner-base:latest
          env:
          - name: OC_URL
            value: ${OC_URL}
      output:
        to:
          kind: ImageStreamTag
          name: 'appuio-pruner:latest'
      resources: {}
      postCommit: {}
    status:
      lastVersion: 0
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: appuio-pruner
      creationTimestamp: null
    spec:
      strategy:
        resources: {}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - appuio-pruner
            from:
              kind: ImageStreamTag
              name: 'appuio-pruner:latest'
      replicas: 1
      test: false
      selector:
        deploymentconfig: appuio-pruner
      template:
        metadata:
          creationTimestamp: null
          labels:
            deploymentconfig: appuio-pruner
          annotations:
            openshift.io/container.appuio-pruner.image.entrypoint: '["/bin/bash"]'
        spec:
          containers:
            - name: appuio-pruner
              image: 'appuio-pruner:latest'
              env:
                - name: TZ
                  value: ${TIMEZONE}
parameters:
  - description: 'APPUiO pruner Git repository'
    name: PRUNER_SOURCE
    value: https://github.com/appuio/appuio-pruner.git
    required: true
  - description: 'APPUiO pruner version, i.e. git ref of the specified repository'
    name: PRUNER_VERSION
    value: master
    required: true
  - description: Base image for pruner, registry.access.redhat.com/rhel7 or centos:7, defaults to the former
    name: BASE_IMAGE
    required: true
    value: registry.access.redhat.com/rhel7
  - description: 'Timezone (TZ) of the container, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for a list'
    name: TIMEZONE
    value: UTC
    required: true
  - description: 'URL of oc client'
    name: OC_URL
    value: https://console.appuio.ch/console/extensions/clients/linux/oc
    required: true
